### PR TITLE
Remove mention of Eglot limitations now gone

### PR DESCRIPTION
**Pull request by joaotavora**
See also: https://github.com/clangd/clangd/issues/183

The limitations mentioned were indeed true at some point, 
but haven't been for a while now.

### CODE REVIEW

**Comment by joaotavora** [comment]
Ping? @sam-mccall ? Can you at least acknowledge the reception of this?  Many thanks.

**Comment by kadircet** [comment]
Thanks and sorry for ignoring this patch silently :( I think we all were aware of it, but since none of us use emacs it is usually really hard to test, and due to recent WFH situation even harder.

I've managed to give it a try today and it seems to be working. I've noticed another issue irrelevant to those though, you might want to take a look. I don't really remember the set of edits i've issued, but I think i had something like:

```
#define FOO(X) X

void foo() {
  FOO // <-- inserted two spaces and then completed FOO through company-mode dropdown.
}
```

which resulted in https://gist.github.com/kadircet/3597eac5f8a89559e29330030e437542

**Comment by joaotavora** [comment]
Thanks @kadircet .  @sam-mccall any chance we can get this merged soon?

I can't quite reproduce  this, can you tell me which `clangd` version you are using?
I'm using 
```
~/S/E/eglot ❯❯❯ clangd --version                                                                                                                                                  ✘ 1 master ✭
clangd version 9.0.0-2 (tags/RELEASE_900/final)
```

**Comment by sam-mccall** [comment]
Sure thing, sorry about the delay.

**Comment by joaotavora** [comment]
Thanks!

**Comment by joaotavora** [comment]
Sam McCall <notifications@github.com> writes:

> Sure thing, sorry about the delay.

Thanks!

**Comment by joaotavora** [comment]
@kadircet the behaviour you were seeing was a bug in yasnippet, Emacs's snippet extension. I just fixed it. So we should be all good.

**Pull request merged**
